INSERT INTO Departments (DepartmentName) VALUES
('Department of Accounting and Finance'),
('Department of Allied Health and Human Performance'),
('Department of Anthropology, Economics and Political Science'),
('Department of Arts and Cultural Management'),
('Department of Biological Sciences'),
('Department of Child and Youth Care'),
('Department of Communication'),
('Department of Computer Science'),
('Department of Decision Sciences'),
('Department of Design'),
('Department of English'),
('Department of Health Systems and Sustainability'),
('Department of Human Health and Science'),
('Department of Human Services and Early Learning'),
('Department of Humanities'),
('Department of International Business, Marketing, Strategy and Law'),
('Department of Management and Organizations'),
('Department of Mathematics and Statistics'),
('Department of Music'),
('Department of Nursing Foundations'),
('Department of Nursing Practice'),
('Department of Physical Sciences'),
('Department of Professional Nursing and Allied Health'),
('Department of Psychology'),
('Department of Public Safety and Justice Studies'),
('Department of Sociology'),
('Department of Studio Arts'),
('Department of Theatre'),
('School of Social Work');